version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - bodyclose
    - dupl
    - goconst
    # - gocritic
    - gocyclo
    - gocognit
    - revive
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    gocyclo:
      min-complexity: 15
    gocognit:
      min-complexity: 15
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    revive:
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/praserx/aegis
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
