name: Package goth test
on: [push, pull_request]
permissions:
  contents: read
jobs:
  style:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.21.x, 1.22.x, 1.23.x, 1.24.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check gofmt
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Code is not gofmt-ed. Run 'gofmt -w .'" && exit 1
          fi
      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - name: Check goimports
        run: |
          if [ -n "$(goimports -l .)" ]; then
            echo "Code is not goimports-ed. Run 'goimports -w .'" && exit 1
          fi
  
  build:
    needs: style
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.21.x, 1.22.x, 1.23.x, 1.24.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build
        run: go build ./...

  test:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.21.x, 1.22.x, 1.23.x, 1.24.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test ./...

  lint:
    needs: test
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.21.x, 1.22.x, 1.23.x, 1.24.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
    